version: "3.8"
services:
    postgres:
        image: postgres:15
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: ipte
        ports:
            - "5432:5432"
        volumes:
            - db-data:/var/lib/postgresql/data
volumes:
    db-data:
